nam = input("Who are you?..")
print("Welcome, ", nam)
nam = input("Why are you here?")
print("I am here to learn everyday", nam)
nam = input("Who introduced you to this?")
print("I got introduced to this by Duupiopikr", nam)
